/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BusinessError: typeof import('./src/utils/errors').BusinessError
  const EffectScope: typeof import('vue').EffectScope
  const ElDialog: (typeof import('element-plus/es'))['ElDialog']
  const ElLoading: (typeof import('element-plus/es'))['ElLoading']
  const ElMessage: (typeof import('element-plus/es'))['ElMessage']
  const ElMessageBox: (typeof import('element-plus/es'))['ElMessageBox']
  const Feedback: typeof import('./src/utils/feedback').Feedback
  const SelfStorage: typeof import('./src/utils/local-storage').SelfStorage
  const [alias]: (typeof import('[package-name]'))['[from]']
  const axios: typeof import('axios').default
  const clipboard: typeof import('./src/utils/clipboard')['default']
  const color: typeof import('./src/utils/color').default
  const compressImg: typeof import('./src/utils/compress')['compressImg']
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createI18nInstance: typeof import('./src/utils/locale').createI18nInstance
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const effectScope: typeof import('vue').effectScope
  const exception: typeof import('./src/utils/errors').exception
  const feedback: typeof import('./src/utils/feedback').default
  const formatLang: typeof import('./src/utils/locale').formatLang
  const generateUUID: typeof import('./src/utils/uuid')['generateUUID']
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const i18n: typeof import('./src/utils/locale')['i18n']
  const image: typeof import('./src/utils/image').default
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const langOptions: typeof import('./src/utils/locale').langOptions
  const locale: typeof import('./src/utils/locale').default
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const normalizeLang: typeof import('./src/utils/locale').normalizeLang
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const removeUrlParam: typeof import('./src/utils/url').removeUrlParam
  const resolveComponent: typeof import('vue').resolveComponent
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const supportedLangs: typeof import('./src/utils/locale').supportedLangs
  const time: typeof import('./src/utils/time').default
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useLockFn: typeof import('./src/hooks/use-lock-fn')['useLockFn']
  const useModel: typeof import('vue').useModel
  const useMouse: typeof import('@vueuse/core').useMouse
  const useMyFetch: typeof import('@vueuse/core').useFetch
  const usePaging: typeof import('./src/hooks/use-paging')['usePaging']
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const withProtocol: typeof import('./src/utils/url').withProtocol
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { BusinessError } from './src/utils/errors'
  import('./src/utils/errors')
  // @ts-ignore
  export type { Feedback } from './src/utils/feedback'
  import('./src/utils/feedback')
  // @ts-ignore
  export type { LangOption } from './src/utils/locale'
  import('./src/utils/locale')
}
